<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listadeventas [
    <!ELEMENT listadeventas (venta+)>
    <!ELEMENT venta (importe,comprador,vendedor,fecha?,codigofactura)>
    <!ELEMENT importe (#PCDATA)>
    <!ELEMENT comprador (#PCDATA)>
    <!ELEMENT vendedor (#PCDATA)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT codigofactura (#PCDATA)>
]>
<listadeventas>
    <venta>
        <importe>100.10</importe>
        <comprador>Paco</comprador>
        <vendedor>Luis</vendedor>
        <fecha>05/04/2024</fecha>
        <codigofactura>0001</codigofactura>
    </venta>
    <venta>
        <importe></importe>
        <comprador>Maria</comprador>
        <vendedor>Luis</vendedor>
        <fecha>05/04/2024</fecha>
        <codigofactura>0002</codigofactura>
    </venta>
</listadeventas>